### ISSUE TITLE
Score-input form validation

### ISSUE THREAD

**Issue by DanRodFox** [katie-mt/golfscoreapp#13]
The process score method requires an int input for each active player. The form will currently error when a score is left omitted.

We will assume every player finishes their round.
A friendly reminder to fill out all the scores before submitting the form would be nice.

Should this be handled using JS or should this go into the controller/template as error handling?

**Comment by jjames1011** [comment]
We could make it to where if a score is left ommitted it defaults to 0 on their score card.

**Comment by DanRodFox** [comment]
That will work to pass the form, and we'll need to think about how a 0 will impact the score down the road. 

If there is a time we compare score to par, a 0 may complicate that calculation. 

Another option would be to default the score to the holes par.
