### ISSUE TITLE
Multiple round functionality

### ISSUE THREAD

**Issue by DanRodFox** [katie-mt/golfscoreapp#21]
No way to proceed to round 2 after 18 holes have been complete. The page is redirected to the leaderboard after 18 holes.

We would like to solve for the user story of a tournament being completed over the course of multiple rounds.

**Comment by armenjuhl** [comment]
Round Number issue for leaderboard printout after round 1 (Showing as round instead of round 1)

**Comment by armenjuhl** [comment]
Multiple Round Functionality has been added. I will push upon one peer-review
