### ISSUE TITLE
Leaderboard controller was listed twice in the Main file

### ISSUE THREAD

**Issue by armenjuhl** [katie-mt/golfscoreapp#35]
Please remove the second leaderboard controller. It will look like this

@app.route("/leaderboard", methods=['GET'])
def display_leaderboard():
    if request.method == 'GET':
        player1 = Score.query.filter_by(player_id==1)
        player2 = Score.query.filter_by(player_id==2)
        player3 = Score.query.filter_by(player_id==3)
        player4 = Score.query.filter_by(player_id==4)
    return render_template("leaderboard.html,")

**Comment by jjames1011** [comment]
fixed in the leaderboard_update branch
