### ISSUE TITLE
Fix being able to add 'empty' players.

### ISSUE THREAD

**Issue by jjames1011** [katie-mt/golfscoreapp#45]
As of now if you do not fill out one of the four player name fields when starting a tournament, the app will not crash, instead it will just present the score_input.html page with a missing name. (this works with all four names being missing). Essentially add some validation to these inputs.

**Comment by DanRodFox** [comment]
I added this validation a while back and the code was lost during a merge. I'll try to find it and bring it back into develop branch.

**Comment by DanRodFox** [comment]
This has been addressed and pushed to develop.
